bella_cuccina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler403, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('shopping_cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('customer_profile.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contact_about/', include('contact_about.urls')),
    path('review/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler500 = handler500
handler403 = handler403

contact_about/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'contact_about'

urlpatterns = [
     path('', views.contact_about, name='contact_about'),
]

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('products/', views.store_products, name='store_products'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),

]

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'shopping_cart'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<product_id>/', views.update_cart, name='update_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('get_cart_total/', views.get_cart_total, name='get_cart_total'),
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_total/', views.wishlist_total, name='wishlist_total'),
]

templates/partials/delete_modal.html
<div class="modal fade " tabindex="-1" id="modal_{{product_id}}">
    <div class="modal-dialog custom-modal-dialog ">
      <div class="modal-content">
        <div class="modal-header p-2">
          <p class="modal-title fw-bold">You are Deleting</p>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="custom-content">{{ product.name}} from shopping cart</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger remove-item" id="remove_{{ product_id }}">Delete</button>
          <button class="btn btn-primary" data-bs-dismiss="modal">Go back</button>


        </div>
      </div>
    </div>
</div>

templates/partials/error_modal_ajax.html
<div class="modal fade " tabindex="-1" id="errorModal">
    <div class="modal-dialog custom-modal-dialog ">
      <div class="modal-content">
        <div class="modal-header p-2">
          <p class="h4 modal-title fw-bold">ERROR</p>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="error-content text-danger"></p>
        </div>
        <div class="modal-footer">

          <button class="btn btn-primary" onclick="window.location.reload()" data-bs-dismiss="modal">CLOSE</button>
        </div>
      </div>
    </div>
</div>

templates/partials/footer.html
<div class="footer-dark container-fluid">
    <footer class="pb-xl-0 pb-md-5 py-sm-5">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 item">
                    <img src="{{ MEDIA_URL }}logo.png" alt="" class="border border-dark img-fluid">
                </div>
                <div class="col-md-6 item text">
                    <h3>Bella Cuccina Market</h3>
                    <p>
                        BellaCuccina Market was born out of a love for authentic Italian food
                         and a desire to share the unparalleled quality and tradition of Italian
                          ingredients with food enthusiasts around the world. From the rolling
                           hills of Tuscany to the sun-drenched coastlines of Sicily, we source our
                            products from trusted artisans and farmers who take pride in their craft, 
                            ensuring that every item meets the highest standards of quality and taste.
                    </p>
                </div>
                <div class="col item social mt-3">
                    <a href="https://www.facebook.com/profile.php?id=61560875649149" target="_blank" aria-label="Facebook icon"><i class="bi bi-facebook" style=" color: #f79250;"></i></a>
                    <a href="https://www.instagram.com/" target="_blank" aria-label="Instagram icon"><i class="bi bi-instagram" style=" color: #f79250;"></i></a>
                    <a href="https://github.com/" target="_blank" aria-label="github  icon"><i class="bi bi-github" style=" color: #f79250;"></i></a>
                </div>
            </div>
            <p class="copyright"> by Bogdan Maria © 2024</p>
        </div>
    </footer>
</div>

templates/partials/top_main_nav.html
<!-- Main navigation -->
<nav class="navbar top navbar-expand-lg navbar-light py-0">
    <div class="container-fluid">
        <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasExample-left " aria-label="sidebar opening button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{{ MEDIA_URL }}logo.png" alt="" class="my-logo img-fluid">
        </a>
        <div class="d-flex d-lg-none align-items-center">
            <div class="dropdown d-none d-xl-block d-lg-block">
                <button type="button" id="dropdownProfile1" class="btn dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false" aria-label="user profile dropdown menu button">
                    <i class="bi bi-person" style="font-size:1.5rem; -webkit-text-stroke-width: 1px;"></i></button>

                <ul class="dropdown-menu " aria-labelledby="dropdownProfile1">
                    {% if request.user.is_authenticated %}
                    <li><a class="dropdown-item " href="{% url 'customer_profile:profile' %}">
                            Profile</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_signup' %}">Register</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <li><a class="dropdown-item " href="{% url 'products:add_product' %}">Shop management</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="position-relative d-none d-xl-block d-lg-block">
                <a href="{% url 'wishlist:wishlist' %}" role="button" class="btn py-3" aria-label="wishlist button ">
                    <i class="bi bi-suit-heart"
                        style="font-size:1.5rem; -webkit-text-stroke-width: 1px; color: white"></i>
                </a>
                <span class="heart-total">{{ wishlist_count}}</span>
            </div>

            <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample-right"
                aria-label="right sidebar opening button">
                <i class="bi bi-search" style="font-size:1.2rem; -webkit-text-stroke-width: 1px; color: white;"></i>
            </button>
            <div>
                <a class="btn py-3" role="button" href="{% url 'shopping_cart:cart' %}" aria-label="View Cart icon">
                    <i class="bi bi-cart3" style="font-size:1.2rem; -webkit-text-stroke-width: 1px; color: white;"></i>
                </a>
                <span class="cart-total">
                    {% if all_items %}
                    {{ all_items }}
                    {% else %}
                    0
                    {% endif %}
                </span>
                <div class="price text-success position-absolute fw-bold"></div>
            </div>
        </div>


        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        All Products
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?sort=price&direction=asc">By Price</a></li>
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?sort=weight&direction=desc">By Weight</a></li>
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?sort=category&direction=asc">By Category</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'products:store_products' %}">All Products</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'products:store_products' %}?category=Pasta">Pasta</a>
                        </li>
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?category=FreshProduce">Fresh Produce</a></li>
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?category=CuredMeats">Cured Meats</a></li>
                        <li><a class="dropdown-item"
                                href="{% url 'products:store_products' %}?category=Pasta,FreshProduce,CuredMeats">All
                                Categories</a></li>
                    </ul>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'contact_about:contact_about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'contact_about:contact_about' %}#contact">Contact</a>
                </li>
            </ul>
            <div class="d-none d-lg-flex flex-row w-auto align-items-center">
                <div class="dropdown">

                    <button type="button" id="dropdownProfile2" class="btn dropdown-toggle text-white shadow-none position-relative" data-bs-toggle="dropdown"
                        aria-expanded="false" aria-label="user profile dropdown menu">
                        <i class="bi bi-person" style="font-size:1.5rem; -webkit-text-stroke-width: 1px;"></i>
                        <span class="text-white user-name">{{ request.user.username|truncatechars:12 }}</span>
                    </button>

                    <ul class="dropdown-menu " aria-labelledby="dropdownProfile2">
                        {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item " href="{% url 'customer_profile:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_signup' %}">Register</a></li>
                        {% endif %}
                        {% if request.user.is_superuser %}
                        <li><a class="dropdown-item " href="{% url 'products:add_product' %}">Shop management</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="position-relative">
                    <a href="{% url 'wishlist:wishlist' %}" role="button" class="btn py-3"
                        aria-label="wishlist button ">
                        <i class="bi bi-suit-heart"
                            style="font-size:1.3rem; -webkit-text-stroke-width: 1px; color: white"></i>
                    </a>
                    <span class="heart-total">{{ wishlist_count}}</span>
                </div>
                <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample-right"
                    aria-label="right sidebar button">
                    <i class="bi bi-search" style="font-size:1rem; -webkit-text-stroke-width: 1px;"></i>
                </button>
                <div>
                    <a class="btn py-3" role="button" href="{% url 'shopping_cart:cart' %}" aria-label="View Cart icon">
                        <i class="bi bi-cart3"
                            style="font-size:1.2rem; -webkit-text-stroke-width: 1px; color: white"></i>
                    </a>
                    <span class="cart-total">{{ all_items }}</span>
                    <div class="price text-warning position-absolute fw-light">
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<!-- main navigation -->

<!-- right sidebar nav -->
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample-right"
    aria-labelledby="right-offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="right-offcanvasExampleLabel">Search the Store</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form class="d-flex " method="GET" action="{% url 'products:store_products' %}">
            <div class="input-group">
                <label for="search-input" class="visually-hidden">Search</label>
                <input class="form-control" id="search-input" type="search" name='q' placeholder="Search"
                    aria-label="Search submit button">
                <button class="btn" type="submit"><i class="bi bi-search"
                        style="font-size:1.2rem; color: white"></i></button>

            </div>
        </form>

    </div>
</div>

<!-- /right sidebar nav -->

<!-- left sidebar nav -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample-left"
    aria-labelledby="left-offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="left-offcanvasExampleLabel">Title left</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    All Products
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'products:store_products' %}?sort=price&direction=asc">By
                            Price</a></li>
                    <li><a class="dropdown-item"
                            href="{% url 'products:store_products' %}?sort=weight&direction=desc">By Weight</a></li>
                    <li><a class="dropdown-item"
                            href="{% url 'products:store_products' %}?sort=category&direction=asc">By Category</a></li>
                    <li><a class="dropdown-item" href="{% url 'products:store_products' %}">All Products</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Categories
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'products:store_products' %}?category=Pasta">Pasta</a>
                    </li>
                    <li><a class="dropdown-item" href="{% url 'products:store_products' %}?category=FreshProduce">Fresh
                            Produce</a></li>
                    <li><a class="dropdown-item" href="{% url 'products:store_products' %}?category=CuredMeats">Cured
                            Meats</a></li>
                    <li><a class="dropdown-item"
                            href="{% url 'products:store_products' %}?category=Pasta,FreshProduce,CuredMeats">All
                            Categories</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'contact_about:contact_about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'contact_about:contact_about' %}#contact">Contact</a>
            </li>
        </ul>
    </div>
</div>