bella_cuccina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler403, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('shopping_cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('customer_profile.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contact_about/', include('contact_about.urls')),
    path('review/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler500 = handler500
handler403 = handler403

checkout/urls.py
from django.contrib import admin
from django.urls import path
from .webhooks import webhook

from . import views


app_name = 'checkout'

urlpatterns = [
    path('', views.store_checkout, name='store_checkout'),
    path('checkout_success/<order_number>', views.checkout_success,
         name='checkout_success'),
    path('wh/', webhook, name='webhook'),
    path('cache_checkout_data/', views.cache_checkout_data,
         name='cache_checkout_data'),
]

customer_profile/urls.py
from django.urls import path
from . import views


app_name = 'customer_profile'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>/',
         views.order_history, name='order_history'),
]

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('products/', views.store_products, name='store_products'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),

]

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'shopping_cart'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<product_id>/', views.update_cart, name='update_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('get_cart_total/', views.get_cart_total, name='get_cart_total'),
]

checkout/models.py
from django.db import models
import uuid
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from products.models import Product
from customer_profile.models import CustomerProfile


class Order(models.Model):
    order_number = models.CharField(max_length=34, null=False, editable=False)
    user_profile = models.ForeignKey(CustomerProfile,
                                     on_delete=models.SET_NULL, null=True,
                                     blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="(select country)")
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        """
        self.grand_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.order_total = self.grand_total
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number

class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, 
                              on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, 
                                blank=False, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, 
                                         null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number

checkout/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'phone_number',
                  'street_address1', 'street_address2',
                  'town_or_city', 'postcode', 'country',
                  'county',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'postcode': 'Postal Code',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'county': 'County, State or Locality',
        }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

checkout/views.py
from django.shortcuts import (render, redirect,
                              reverse, HttpResponse, get_object_or_404)
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.conf import settings
import math
import stripe
import json

from .forms import OrderForm
from .models import Order, OrderLineItem
from products.models import Product
from shopping_cart.context import cart_content
from customer_profile.models import CustomerProfile
from customer_profile.forms import CustomerProfileForm


@require_POST
def cache_checkout_data(request):
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'cart': json.dumps(request.session.get('cart', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request,
                       'Sorry we cant process your payment at the moment\
                        plaease try later!')
        return HttpResponse(status=400)


def store_checkout(request):

    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        cart_data = request.session.get('cart', {})

        form_data = {
            'full_name': request.POST['full_name'],
            'email': request.POST['email'],
            'phone_number': request.POST['phone_number'],
            'country': request.POST['country'],
            'postcode': request.POST['postcode'],
            'town_or_city': request.POST['town_or_city'],
            'street_address1': request.POST['street_address1'],
            'street_address2': request.POST['street_address2'],
            'county': request.POST['county'],
        }
        order_form = OrderForm(form_data)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            pid = request.POST.get('client_secret').split('_secret')[0]
            order.stripe_pid = pid
            order.original_cart = json.dumps(cart_data)
            order.save()
            for product_id, cart_item in cart_data.items():
                try:
                    product = Product.objects.get(id=product_id)
                    if isinstance(cart_item['qty'], int):
                        order_line_item = OrderLineItem(
                            order=order,
                            product=product,
                            quantity=cart_item['qty'],
                        )
                        order_line_item.save()

                except Product.DoesNotExist:
                    messages.error(request, (
                        "One of the products in your bag wasn't found in our database. "
                        "Please call us for assistance!")
                    )
                    order.delete()
                    return redirect(reverse('shopping_cart:cart'))

            request.session['save_info'] = 'save-info' in request.POST
            return redirect(reverse('checkout:checkout_success', args=[order.order_number]))
        else:
            messages.error(request, 'There was an error with your form. \
                Please double check your information.')

    else:
        cart_data = request.session.get('cart', {})
        if not cart_data:
            messages.error(request, "Your Shopping cart is empty")
            return redirect(reverse('products:store_products'))

        current_cart = cart_content(request)
        total = current_cart['total']
        stripe_total = round(total*100)
        stripe.api_key = stripe_secret_key
        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY,
        )

        if request.user.is_authenticated:
            try:
                profile = CustomerProfile.objects.get(user=request.user)
                order_form = OrderForm(initial={
                    'full_name': profile.user.get_full_name(),
                    'email': profile.user.email,
                    'phone_number': profile.default_phone_number,
                    'country': profile.default_country,
                    'postcode': profile.default_postcode,
                    'town_or_city': profile.default_town_or_city,
                    'street_address1': profile.default_street_address1,
                    'street_address2': profile.default_street_address2,
                    'county': profile.default_county,

                })

            except CustomerProfile.DoesNotExist:
                order_form = OrderForm()
        else:
            order_form = OrderForm()

    if not stripe_public_key:
        messages.warning(request, 'Stripe public key is missing. \
            Did you forget to set it in your environment?')

    context = {
        'order_form': order_form,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret,
    }

    return render(request, 'checkout/checkout.html', context)


def checkout_success(request, order_number):
    """
    Handle successful checkouts
    """
    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_number=order_number)
    if request.user.is_authenticated:
        profile = CustomerProfile.objects.get(user=request.user)
        # Attach the user's profile to the order
        order.user_profile = profile
        order.save()

    # Save the user's info
    if save_info:
        profile_data = {
            'default_phone_number': order.phone_number,
            'default_country': order.country,
            'default_postcode': order.postcode,
            'default_town_or_city': order.town_or_city,
            'default_street_address1': order.street_address1,
            'default_street_address2': order.street_address2,
            'default_county': order.county,
        }
        user_profile_form = CustomerProfileForm(profile_data, instance=profile)
        if user_profile_form.is_valid():
            user_profile_form.save()
    messages.success(request, f' Your Order was successfully processed! \
        Your order number is:{order_number}. A confirmation \
        email will be sent to {order.email}.')

    if 'cart' in request.session:
        del request.session['cart']

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
    }

    return render(request, template, context)

checkout/templates/checkout/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tool %}

{% block content %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock  %}



{% include 'partials/top_main_nav.html' %}


<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4" id="check">Checkout</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-lg-6 order-lg-last mb-5">
            <p class="text-muted">Order Summary<span class="cart-total"> {{ all_items }}</span></p>
            <div class="row">
                <div class="col-7 offset-2">
                    <p class="mb-1 mt-0 small text-muted">Item</p>
                </div>
                <div class="col-3 text-right">
                    <p class="mb-1 mt-0 small text-muted">Subtotal</p>
                </div>
            </div>
            {% for item in cart_items %}
            <div class="row">
                <div class="col-2 mb-1">
                    <a href="">
                        {% if item.product.image %}
                        <img class="w-100" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                        {% else %}
                        <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="default image for products without image uploaded">
                        {% endif %}
                    </a>
                </div>
                <div class="col-7">
                    <p class="my-0"><strong>{{ item.product.name }}</strong></p>
                    <p class="my-0 text-muted">({{ item.quantity }} x ${{ item.product.price }})</p>

                </div>
                <div class="col-3 text-right">
                    <!-- <p class="my-0 small text-muted">${{ item.product.price }}</p> -->
                    <p class="my-0 small text-muted">
                        $ {{ item.product.price | calc_subtotal:item.quantity }}
                </div>
            </div>
            {% endfor %}
            <hr class="my-0">
            <div class="row text-black text-right">
                <div class="col-7 offset-2">
                    <p class="my-0">Order Total:</p>

                    <!-- <p class="my-0">Grand Total:</p> -->
                </div>
                <div class="col-3">
                    <p class="my-0">${{ total | floatformat:2 }}</p>

                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6">
            <p class="text-muted">Please fill out the form below to complete your order</p>
            <form action="{% url 'checkout:store_checkout' %}" method="POST" id="payment-form">
                {% csrf_token %}
                <fieldset class="rounded px-3 mb-5">
                    <legend class="fieldset-label small text-black px-2 w-auto">Details</legend>
                    {{ order_form.full_name | as_crispy_field}}
                    {{ order_form.email | as_crispy_field  }}
                </fieldset>
                <fieldset class="rounded px-3 mb-5">
                    <legend class="fieldset-label small text-black px-2 w-auto">Delivery</legend>
                    {{ order_form.phone_number | as_crispy_field }}
                    {{ order_form.street_address1 | as_crispy_field }}
                    {{ order_form.street_address2 | as_crispy_field }}
                    {{ order_form.town_or_city | as_crispy_field }}
                    {{ order_form.county | as_crispy_field }}
                    {{ order_form.postcode | as_crispy_field }}
                    {{ order_form.country | as_crispy_field }}
                    <div class="d-flex">
                        {% if user.is_authenticated %}
                        <label class="form-check p-0 me-2 text-muted" for="id-save-info">Save this delivery information to my
                            profile</label>
                        <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-save-info" name="save-info"
                            checked>
                        {% else %}
                        <label class="form-check">
                            <a class="text-info" href="{% url 'account_signup' %}">Create an account</a> or
                            <a class="text-info" href="{% url 'account_login' %}">login</a> to save this information
                        </label>
                        {% endif %}
                    </div>
                </fieldset>
                <fieldset class="px-3">
                    <legend class="fieldset-label small text-black px-2 w-auto">Payment</legend>
                    <!-- A Stripe card element will go here -->
                    <div class="mb-3" id="card-element"></div>
                    <!-- Used to display form errors -->
                    <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
                    <!-- Pass the client secret to the view so we can get the payment intent id -->
                    <input type="hidden" value="{{ client_secret }}" name="client_secret">
                </fieldset>

                <div class="submit-button text-right mt-5 mb-2">
                    <a href="{% url 'shopping_cart:cart' %}" class="btn btn-warning rounded-0" aria-label="Adjust shopping cart link">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="font-weight-bold">Adjust Bag</span>
                    </a>
                    <button id="submit-button" class="btn btn-success rounded-0">
                        <span class="font-weight-bold">Complete Order</span>
                        <span class="icon">
                            <i class="fas fa-lock"></i>
                        </span>
                    </button>
                    <p class="small text-danger my-0">
                        <span class="icon">
                            <i class="fas fa-exclamation-circle"></i>
                        </span>
                        <span>Your card will be charged <strong>${{ total|floatformat:2 }}</strong></span>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
{% include 'partials/footer.html' %}
<div id="loading-overlay">
    <h1 class="text-light logo-font loading-spinner">
        <span class="">
            <img src="{{ MEDIA_URL }}logo.png" alt="webshop Logo" class="fade-in-out img-fluid">
        </span>
    </h1>
</div>

{% endblock %}

{% block postload_js%}
{{ block.super }}
{{ stripe_public_key|json_script:"id_stripe_public_key" }}
{{ client_secret|json_script:"id_client_secret" }}
<script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
{% endblock %}

checkout/templates/checkout/checkout_success.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}


{% block content %}
{% include 'partials/top_main_nav.html' %}
<div class="overlay"></div>
<div class="container checkout-success bg-light mt-3 border border-success" style="max-width: 550px !important;">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4">Thank You for your order</h2>
            <hr>
            <p class="text-black">Your order information is below. A confirmation email will be sent to
                <strong>{{ order.email }}</strong>.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-lg-7"></div>
        <div class="col-12 text-md-left mb-3">
            <small class="text-muted font-italic p-md-l-3">Order Info</small>
        </div>

        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Order Number:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.order_number }}</p>
        </div>

        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Order Date:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.date }}</p>
        </div>
    </div>
    <hr class="email-rule">

    <div class="row">
        <div class="col-12 text-md-left mb-3">
            <small class="text-muted font-italic p-md-l-3">Order Details</small>
        </div>
    </div>

    {% for item in order.lineitems.all %}
    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">{{ item.product.name }}</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="small mb-0  p-md-r-3">{{ item.quantity }} x ${{ item.product.price }} each</p>
        </div>
    </div>
    {% endfor %}

    <hr class="email-rule">

    <div class="row">
        <div class="col-12 text-md-left mb-3">
            <small class=" p-md-l-3">Delivery Address</small>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Full Name:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.full_name}}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Address 1:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.street_address1 }}</p>
        </div>
    </div>
    {% if order.street_address2 %}
    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Address 2:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.street_address2 }}</p>
        </div>
    </div>
    {% endif %}

    {% if order.county %}
    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">County:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.county }}</p>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Town or City:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.town_or_city }}</p>
        </div>
    </div>

    {% if order.eircode %}
    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Eircode:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.eircode }}</p>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Country:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.country }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Phone Number:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">{{ order.phone_number }}</p>
        </div>
    </div>

    <hr class="">

    <div class="row">
        <div class="col-12 text-md-left mb-3">
            <small class="text-muted font-italic p-md-l-3">Billing Information</small>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Order Total:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right">
            <p class="mb-0 p-md-r-3">${{ order.order_total }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-4 text-md-left">
            <p class="mb-0 text-black font-weight-bold p-md-l-3">Grand Total:</p>
        </div>
        <div class="col-12 col-md-8 text-md-right mb-4">
            <p class="mb-0 p-md-r-3">${{ order.grand_total }}</p>
        </div>
    </div>
</div>

<div class="col-12 text-center my-4">
    <a href="{% url 'products:store_products'%}" class="btn btn-dark ">
        <i class="bi bi-backspace-fill"></i> Back to shop
    </a>
</div>

<div class="col-12 text-center my-4">
    <a href="{% url 'products:store_products'%}" class="btn btn-dark">
        <i class="bi bi-backspace-fill"></i> Back to shop
    </a>
    {% if user.is_authenticated %}
    <a href="{% url 'customer_profile:profile' %}" class=" text-center  btn btn-success">
        Return to Profile
    </a>
    {% else %}
    <a href="{% url 'home:home' %}" class=" text-center btn btn-success">
       Home
    </a>
    {% endif %}
</div>
{% endblock %}