bella_cuccina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler403, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('shopping_cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('customer_profile.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contact_about/', include('contact_about.urls')),
    path('review/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler500 = handler500
handler403 = handler403

customer_profile/urls.py
from django.urls import path
from . import views


app_name = 'customer_profile'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>/',
         views.order_history, name='order_history'),
]

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

customer_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomerProfile(models.Model):
    """
    A user profile model for maintaining default
    delivery information and order history
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    default_phone_number = models.CharField(max_length=20,
                                            null=True, blank=True)
    default_country = CountryField(blank_label='Country *',
                                   null=True, blank=True)
    default_postcode = models.CharField(max_length=20, null=True, blank=True)
    default_town_or_city = models.CharField(max_length=40,
                                            null=True, blank=True)
    default_street_address1 = models.CharField(max_length=80,
                                               null=True, blank=True)
    default_street_address2 = models.CharField(max_length=80,
                                               null=True, blank=True)
    default_county = models.CharField(max_length=80, null=True, blank=True)

    def __str__(self):
        return self.user.username

customer_profile/forms.py
from django import forms
from .models import CustomerProfile


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = CustomerProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {

            'default_phone_number': 'Phone Number',
            'default_postcode': 'Postal Code',
            'default_town_or_city': 'Town or City',
            'default_street_address1': 'Street Address 1',
            'default_street_address2': 'Street Address 2',
            'default_county': 'County, State or Locality',
            'email': 'email',
        }

        self.fields['default_phone_number'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'default_country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'profile-form-input'
            self.fields[field].label = False

customer_profile/views.py
from django.shortcuts import (render, redirect,
                              reverse, HttpResponse, get_object_or_404)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.conf import settings

from customer_profile.models import CustomerProfile
from .forms import CustomerProfileForm
from checkout.models import Order


@login_required
def profile(request):
    """
    view handling user profile
    """
    customer_profile = get_object_or_404(CustomerProfile, user=request.user)
    if request.method == 'POST':
        form = CustomerProfileForm(request.POST, instance=customer_profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Your profile is updated")
        else:
            messages.error(request, 'Failed to update profile please check your form for errors')
    else:
        form = CustomerProfileForm(instance=customer_profile)
    orders = customer_profile.orders.all()
    template = 'customer_profile/profile.html'
    context = {
        'form': form,
        'orders': orders,
        'customer_profile': customer_profile,
        'on_profile_page': True,
    }
    return render(request, template, context)


def order_history(request, order_number):
    order = get_object_or_404(Order, order_number=order_number)
    messages.info(request, (
        f'This is a past confirmation for order number {order_number}. '
        'A confirmation email was sent on the order date.'
    ))

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        'from_profile': True,
    }

    return render(request, template, context)

customer_profile/templates/customer_profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'customer_profile/css/profile.css' %}">
{% endblock %}



{% include 'partials/top_main_nav.html' %}

<h1 class="text-center my-3">My Profile</h1>
<div class="container-fluid">
  <div class="row mx-auto mb-4">
    <div class="col-lg-6 col-md-10 mt-2">
      <!-- accordion -->
      <div class="accordion" id="order-accordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button">
              <strong>Order History </strong>({{ orders|length}})
            </button>
          </h2>
        </div>
        {% for order in orders %}
        <div class="accordion-item">
          <h2 class="accordion-header text-center" id="heading{{ order.order_number|truncatechars:6 }}">
            <button class="accordion-button" type="button" data-bs-toggle="collapse"
              data-bs-target="my_{{ order.order_number}}" aria-expanded="true"
              aria-controls="my_{{ order.order_number }}">
              <span class="text-success">{{ order.order_number|truncatechars:10 }}</span>
            </button>
          </h2>

          <div id="my_{{ order.order_number }}" class="accordion-collapse collapse " aria-labelledby="headingOne"
            data-bs-parent="#order-accordion">
            <div class="accordion-body">
              <div class="">

                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Order num.</th>
                      <!-- <th scope="col">Date</th> -->
                      <th scope="col">Items</th>
                      <th scope="col">Item Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in order.lineitems.all %}
                    <tr>
                      <th scope="row">
                        <a
                          href="{% url 'customer_profile:order_history' order.order_number %}">{{ order.order_number|truncatechars:6 }}</a>
                      </th>
                      <!-- <td>{{ order.date }}</td> -->
                      <td>{{ item.product.name }}({{ item.quantity }})</td>
                      <td>${{ item.product.price }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            <div class="d-flex justify-content-between px-3"> Order-total: <span
                class="mr-3 text-muted">{{ order.date }}</span>
            </div>
            <div class="mt-2 px-3 fw-bold"> ${{ order.grand_total }}
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- accordion -->
      </div>
    </div>
    <div class="col-lg-6 col-md-10 mt-2">
      <form method="POST" class="px-30" id="profile-form">
        {% csrf_token %}
        <table class="table table-borderless mb-0">
          <tbody>
            <tr>
              <th scope="row">Name:</th>
              <td class="fw-bold text-capitalize">{{ customer_profile.user.username }}</td>

            </tr>
            <tr>
              <th scope="row">Address 1:</th>
              <label for="id_default_street_address1"></label>
              <th><span class="d-none"> form address</span>{{ form.default_street_address1|as_crispy_field }}</th>
            </tr>
            <tr>
              <th scope="row">Address 2:</th>
              <label for="id_default_street_address2"></label>
              <th><span class="d-none"> form address</span>{{ form.default_street_address2|as_crispy_field }}</th>
            </tr>
            <tr>
              <th scope="row">Phone number:</th>
              <label for="id_default_phone_number"></label>
              <th><span class="d-none"> form phone number</span>{{ form.default_phone_number|as_crispy_field }}</th>
            </tr>
            <tr>
              <th scope="row">Town or City:</th>
              <label for="id_default_town_or_city"></label>
              <th><span class="d-none"> form town_or_city</span>{{ form.default_town_or_city|as_crispy_field }}</th>
            </tr>
            <tr>
              <th scope="row">County | Post code</th>
              <th><span class="d-none"> form county and postcode</span>
                <label for="id_default_county"></label>{{ form.default_county|as_crispy_field }}
                <label for="id_default_postcode"></label>
                {{ form.default_postcode|as_crispy_field }}</th>
            </tr>
            <tr>
              <th scope="row">Country</th>
              <label for="id_default_country"></label>
              <th>{{ form.default_country|as_crispy_field }}</th>
            </tr>
          </tbody>
        </table>
      </form>
      <div class="d-flex justify-content-end px-4">
        <button class="btn-dark p-1 px-2 fw-bold" type="submit" form="profile-form">
          Update profile
          <i class="bi bi-person"></i>
        </button>
      </div>
    </div>
  </div>
</div>
{% include 'partials/footer.html' %}

{% endblock  %}