bella_cuccina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler403, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('shopping_cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('customer_profile.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('contact_about/', include('contact_about.urls')),
    path('review/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404
handler500 = handler500
handler403 = handler403

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('products/', views.store_products, name='store_products'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),

]

reviews/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('create_review', views.create_review, name='create_review'),
    path('update_review/', views.update_review, name='update_review'),
    path('delete_review/', views.delete_review, name='delete_review'),
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_total/', views.wishlist_total, name='wishlist_total'),
]

products/models.py
from django.db import models
import random
import string


class Category(models.Model):
    """
    class for category model
    """
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    notes = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=254, blank=True, null=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


def random_generated_string():
    not_unique = True
    while not_unique:
        key = random.choice(string.ascii_uppercase) + str(random.randrange(100, 999))
        if not Product.objects.filter(item_no=key):
            not_unique = False
    return str(key)


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    item_no = models.CharField(max_length=254, default=random_generated_string, unique=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    weight = models.IntegerField(null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms

from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib.auth.decorators import login_required

from .models import Product, Category
from .forms import ProductForm
from reviews.models import Review
from reviews.forms import ReviewForm


def store_products(request):

    products = Product.objects.all()
    template = 'products/store_products.html'
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, 'Your search criteria is empty')
                return redirect(reverse('store_products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

        sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'sorting': sort,
    }
    my_product = products.filter(image='')
    print(my_product)
    return render(request, template, context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)
    form = ReviewForm()
    template = 'products/product_details.html'

    context = {
        'product': product,
        'form': form,
        'reviews': reviews,
        'on_products_page': True,
    }

    return render(request, template, context)


@login_required
def add_product(request):
    """
    adding products to a store
    """
    if not request.user.is_superuser:
        messages.error(request, 'SORRY Only store owners have  access')
        return redirect(reverse('home:home'))
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, "New product added successfully")
            return redirect(reverse('products:product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product please check your form for errors')
    else:
        form = ProductForm()
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    editing products from a store
    """
    if not request.user.is_superuser:
        messages.error(request, 'SORRY Only store owners have  access')
        return redirect(reverse('home:home'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f'{product.name} edited successfully')
            return redirect(reverse('products:product_detail', args=[product.id]))
        else:
            messages.error(request, f'Failed Edit {product.name} product please check your form for errors')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editig {product.name}')

    template = 'products/edit_product.html'
    context = {
        'product': product,
        'form': form,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    editing products from a store
    """
    if not request.user.is_superuser:
        messages.error(request, 'SORRY Only store owners have  access')
        return redirect(reverse('home:home'))
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted')
    return redirect(reverse('products:store_products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}



{% block content %}

{% include 'partials/top_main_nav.html' %}
<div class=""></div>
<div class="container pt-4">
    <div class="row">
        <div class="col-12 col-md-6 mt-3 pt-2 pb-3">
            <form enctype="multipart/form-data" method="POST" action="{% url 'products:add_product' %}"
                class="mb-2 product-form ">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.category|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.item_no|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.price|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.description|as_crispy_field }}
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.weight|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.image_url|as_crispy_field }}
                    </div>

                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.image|as_crispy_field }}
                    </div>

                </div>
                <div class="text-right">
                    <a class="btn btn-danger rounded-0" href="">Cancel</a>
                    <button class="btn btn-success rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% include 'partials/footer.html' %}
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}



{% block content %}

{% include 'partials/top_main_nav.html' %}
<div class=""></div>
<div class="container pt-4">
    <div class="row">
        <div class="col-12 col-md-6 mt-3">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h3 class="text-muted">Edit Product-<span class="text-dark fw-bold">{{product.name}}</span>
            </h3>
            <hr>
            <div class="d-flex justify-content-center">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">

                    <img class=" mb-5 mb-md-0" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="{{ MEDIA_URL }}noimage.jpg" target="_blank">
                    <img class=" mb-5 mb-md-0" src="{{ MEDIA_URL }}noimage.jpg" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 mt-3 pb-3 pt-2">
            <form enctype="multipart/form-data" method="POST" action="{% url 'products:edit_product' product.id %}"
                class="mb-2 product-form ">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ form.category|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.item_no|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.price|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.weight|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.image_url|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form.image|as_crispy_field }}
                    </div>
                </div>
                <div class="text-right">
                    <a class="btn btn-danger rounded-0" href="">Cancel</a>
                    <button class="btn btn-success rounded-0" type="submit">Edit Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% include 'partials/footer.html' %}
{% endblock %}

products/templates/products/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'partials/top_main_nav.html' %}
{% include 'partials/delete_product_modal.html' %}

<h2 class="text-center">Product details page</h2>
<div class="container px-4 px-lg-5 my-1 ">
    <div class="row gx-4 gx-lg-5 all_items-start">
        <div class="col-md-6">
            <div class="detail-image-container">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="{{ MEDIA_URL }}no_image.jpg" target="_blank">
                    <img class="card-img-top mb-5 mb-md-0" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <form action="{% url 'wishlist:add_to_wishlist' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="product-id" value="{{ product.id }}">
                <button class="btn btn-dark rounded-0 mt-3" id="wish">Add to wishlist <i
                        class="bi bi-suit-heart-fill"></i></button>
                <input type="hidden" name="my_redirect_url" value="{{ request.path }}">
            </form>
            {% if request.user.is_superuser %}
            <div>
                <small class="ml-3">
                    <a class="btn btn-primary mt-3" href="{% url 'products:edit_product' product.id %}">
                        <i class="bi bi-pencil-square"></i>Edit</a>
                    <button class="btn btn-danger mt-3 shadow-none" aria-label="delete-product-button"
                        data-bs-toggle="modal" data-bs-target="#modal_{{product_id}}">
                        <i class="bi bi-trash3"></i>

                    </button>
                </small>
            </div>
            {% endif %}
            <div class="small mb-1 mt-1">Item No: {{product.item_no}}</div>
            <h1 class="display-5 fw-bolder product-name">{{ product.name }}</h1>
            <div class="fs-5 mb-3">
                <span class="text-success fw-bold">€ {{product.price}}</span>

            </div>
            <p class="lead">{{ product.description }}</p>
            <div class="handle">Weight: <strong>{{ product.weight }} grams</strong>
            </div>
            <!-- hidden inputs for ajax call -->
            <input type="hidden" class="product-id" value="{{ product.id }}">
            {% if product.image %}
            <input type="hidden" class="product-image" value="{{ product.image.url }}">
            {% else %}
            <input type="hidden" class="product-image" value="{{ MEDIA_URL }}noimage.png">
            {% endif %}
            <input type="hidden" class="product-price" value="{{ product.price }}">
            <!-- end  -->
            <div class="counter">
                <form class="form" method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="csrf_token" value="{{ csrf_token }}">
                    <div class="form-row">
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="error-qty"></div>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-danger rounded-0"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input product-qty" type="number" name="quantity"
                                        value="1" min="1" max="10" data-item_id="{{ product.id }}"
                                        id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-success rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col{% if s %}-12 mt-2{% endif %}">

                            <a href="{% url 'products:store_products'%}" class="btn btn-secondary rounded-0 mt-3">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase"> Shop</span>
                            </a>
                            <button type="button" id="addToCartBtn"
                                class="btn btn-success flex-shrink-0 text-uppercase mt-3">
                                <i class="bi-cart-fill me-1"></i>Add to cart</button>
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- </section> -->
<!-- reviews -->
<div class="container-fluid">
    <div class="d-flex justify-content-center row">
        <div class="d-flex flex-column col-md-8">
            <div class=" text-center comment-top p-2 bg-light border-bottom px-4 mt-2">
                <h3>Reviews</h3>
            </div>
            <div class="commented-section mt-2 ">
                {% for review in reviews %}
                {% include 'partials/delete_modal_review.html' %}
                <div class="user-comments mt-2 pb-0 border">

                    <div class="d-flex flex-column align-items-start commented-user mt-2 mb-2">
                        <div class="d-flex gap-2 ">
                            <h5 class="mr-2 mb-0 ml-1 fw-bold text-capitalize">{{ review.author }} </h5>
                            <small
                                class="timestamp text-muted text-decoration-underline bg-white">{{ review.time_posted|timesince }}
                                ago</small>
                        </div>
                        ⭐️⭐️⭐️⭐️⭐️
                    </div>

                    <div class="comment-text-sm review_content" data-id="{{ review.id }}">
                        <span>{{ review.content }}</span>
                        <div class="d-flex justify-content-end">
                            {% if request.user == review.author %}
                            <button class="btn edit_review py-0 edit_reviewtext-primary shadow-none"
                                aria-label="update-review-button">
                                <i class="bi bi-pencil-square"
                                    style="font-size:1.2rem; -webkit-text-stroke-width: 1px;"></i>
                            </button>
                            <button class="btn  mt-3 text-danger shadow-none" aria-label="delete-product-button"
                                data-bs-toggle="modal" data-bs-target="#modal_{{ review.id }}">
                                <i class="bi bi-trash" style="font-size:1.2rem; -webkit-text-stroke-width: 1px;"></i>
                            </button>
                            {% else %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
            {% if user.is_authenticated %}
            <div class="coment-bottom bg-white p-2 pe-4 ps-0">
                <div class=" add-comment-section mt-4 mb-4">
                    <form class="review-form w-50" data-create-review-url="{% url 'reviews:create_review' %}"
                        method="POST">
                        {% csrf_token %}
                        <!-- ajax cal hidden inputs -->
                        <input type="hidden" id="csrf" value="{{ csrf_token }}">
                        <input type="hidden" id="edit-url" value="{% url 'reviews:update_review' %}">
                        <input type="hidden" name="review-id" id="review-id" value="{{ review.id }}">
                        <!-- <input type="hidden" id="current-time" value="{{ csrf_token }}"> -->
                        <input type="hidden" name="current_time" value="{{ review.time_posted }}">
                        <input type="hidden" class="product-id" value="{{ product.id}}">
                        <input type="hidden" class="default-product-id" value="{{ product.id}}">
                        <input type="hidden" class="user" value="{{ request.user.username}}">
                        {{ form|crispy }}
                        <button class="btn btn-primary  mt-0 add_review" type="submit">Add Review</button>
                    </form>
                </div>
                <input type="hidden" id="delete-url" value="{% url 'reviews:delete_review' %}">
            </div>
        </div>
        {% else %}
        <div class="my-4 text-center fw-bold"> <a href="{% url 'account_login' %}" class="text-primary">To add a review
                you need to log in</a> </div>

        {% endif %}
    </div>
</div>
{% include 'partials/footer.html' %}

{% endblock %}

{% block postload_js%}
{{ block.super }}
<script src="{% static 'reviews/js/reviews.js' %}"></script>
{% include 'partials/quantity_input_script.html' %}

{% endblock %}

products/templates/products/store_products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'partials/top_main_nav.html' %}

<div class="container-fluid mt-3 mb-1 bg-light">
    <h1 class="text-center text-uppercase">
        {% if current_categories %}
            {% if current_categories|length == 1%}
            {% for category in current_categories %}
            {{category}} PRODUCTS
            {% endfor %}
            {% else %}
            ALL PRODUCTS
            {% endif %}
        {% else %}
        All PRODUCTS
        {% endif %}
    </h1>
    <div class="row">
        <div class="row mt-1 d-flex justify-content-around mx-auto">
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 my-auto d-flex justify-content-center">
                <div class="sort-select-wrapper">
                    <label for="sort-selector">Sort By:</label>
                    <select id="sort-selector"
                        class="custom-select p-1 custom-select-sm rounded-2 border border-{% if sorting != 'None_None' %}info{% else %}black{% endif %}">
                        <option value="reset" {% if sorting == 'None_None' %}selected{% endif %}>Filter</option>
                        <option value="price_asc" {% if sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
                        </option>
                        <option value="price_desc" {% if sorting == 'price_desc' %}selected{% endif %}>Price (high to
                            low)</option>
                        <option value="weight_asc" {% if sorting == 'weight_asc' %}selected{% endif %}>Product Weight
                            (low to high)</option>
                        <option value="weight_desc" {% if sorting == 'weight_desc' %}selected{% endif %}>Product Weight
                            (high to low)</option>
                        <option value="name_asc" {% if sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                        <option value="name_desc" {% if sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                        <option value="category_asc" {% if sorting == 'category_asc' %}selected{% endif %}>Category
                            (A-Z)</option>
                        <option value="category_desc" {% if sorting == 'category_desc' %}selected{% endif %}>Category
                            (Z-A)</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4  order-md-last">
                <p class="text-muted mt-3 text-center text-md-left">
                    {% if search_term or current_categories or sorting != 'None_None' %}
                    {% endif %}
                    {{ products|length }} Products{% if search_term %} found for
                    <strong>"{{ search_term }}"</strong>{% endif %}
                </p>
            </div>
        </div>

        <!-- sorting option -->
    </div>

    <div class="row">
        <div class="mycontainer ">
            {% for product in products %}
            <div class="product-card">
                <div class="product-card__images">
                    <div class="product-card__img">
                        {% if product.image %}
                        <a href="{% url 'products:product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="{% url 'products:product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                        {% endif %}
                    </div>
                    <div class="product-card__like">
                        <form action="{% url 'wishlist:add_to_wishlist' %}" method="POST" enctype = "multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" name="product-id" value="{{ product.id }}" >
                            <button type="submit" class="btn heart" aria-label="Add to wishlist button"><i class="product-card__heart bi bi-suit-heart" style="font-size: 2rem;-webkit-text-stroke-width: 1px;"></i></button>
                            <input type="hidden" name="my_redirect_url" value="{{ request.path }}">
                        </form>
                    </div>
                    <a href="{% url 'products:product_detail' product.id %}" class="btn product-card__btn">See more</a>
                </div>
                <div class="product-card__info">
                    <div class="d-flex justify-content-between align-items-center flex-wrap ">
                        <h6 class="mb-0 fw-bold">{{ product.name }}</h6>|<span
                            class="text-muted ">Weight:{{ product.weight }} grams</span>
                    </div>
                    <div class="text-start">
                        <span class="text-success fw-bold">{{ product.price }} $</span>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mt-2">
                        {% if product.category  %}
                        <div class="ratings">{{ product.category.name }} </div>
                        {% else %}
                        {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            <div class="all_products">
                                <a class="btn addToCartBtn" aria-label="Add to cart button" href="#">
                                    <i class="bi bi-cart-check" style="-webkit-text-stroke-width: 1.5px; font-size: 1.5rem; color: rgb(8, 143, 14);"></i>
                                </a>
                                <!-- hidden inputs for ajax call -->
                                <input type="hidden" class="product-id" value="{{ product.id }}" >
                                {% if product.image %}
                                <input type="hidden" class="product-image" value="{{ product.image.url }}" >
                                {% else %}
                                <input type="hidden" class="product-image" value="{{ MEDIA_URL }}noimage.png" >
                                {% endif %}
                                <input type="hidden" class="product-price" value="{{ product.price }}">
                                <input type="hidden" class="product-name" value="{{ product.name }}">
                                <input type="hidden" class="csrf_token" value="{{ csrf_token }}">
                                <a class="btn" href="{% url 'products:product_detail' product.id %}"><i class="bi bi-eye-fill" style=" font-size: 1.5rem;"></i> </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% include 'partials/footer.html' %}
<div class="btt-button">
    <a class="back-to-top d-flex h-100">
        <i class="bi bi-arrow-up-square-fill" id="back-to-top"></i>
    </a>
</div>

{% endblock %}